# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [3]:
import numpy as np

#### 2. Print your NumPy version.

In [4]:
print(np)

<module 'numpy' from '/Users/Veeka/anaconda/lib/python3.4/site-packages/numpy/__init__.py'>


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [10]:
# Method 1
a = np.random.random((2,3,5))
print(a)

[[[ 0.34897139  0.15142633  0.58206995  0.21390391  0.34324816]
  [ 0.91654477  0.80973979  0.02136075  0.4921102   0.18634341]
  [ 0.32089766  0.14580275  0.92789803  0.46102743  0.37662616]]

 [[ 0.93754089  0.1953373   0.8048681   0.28495007  0.00244941]
  [ 0.67133409  0.79053187  0.90486799  0.10373311  0.25350126]
  [ 0.71970351  0.75921907  0.72591085  0.95488176  0.12928228]]]


In [11]:
# Method 2
a = np.random.rand(2,3,5)
print(a)

[[[ 0.91252332  0.60493547  0.59908199  0.37560544  0.90829198]
  [ 0.50390017  0.86165301  0.98656726  0.23714019  0.61991885]
  [ 0.50821839  0.71220113  0.40130057  0.18118954  0.44860378]]

 [[ 0.08797017  0.79650572  0.12177685  0.96283688  0.32615171]
  [ 0.65594566  0.91062848  0.59086303  0.77358489  0.26337469]
  [ 0.47352512  0.88145818  0.40812382  0.76968062  0.84903353]]]


In [12]:
# Method 3 
import random
a = np.array([[[random.random() for i in range(5)] for j in range(3)] for k in range(2)])
print(a)

[[[ 0.72290205  0.10659068  0.65724085  0.74422644  0.95280503]
  [ 0.22185243  0.21969498  0.31722055  0.50998096  0.54131707]
  [ 0.78368751  0.18323387  0.2906823   0.17414157  0.96490528]]

 [[ 0.89435886  0.96986971  0.71229997  0.37792392  0.38869377]
  [ 0.65646515  0.12495514  0.29072727  0.27348403  0.41487682]
  [ 0.09558783  0.12397421  0.97410633  0.14579298  0.24608502]]]


#### 4. Print *a*.


In [13]:
print(a)

[[[ 0.72290205  0.10659068  0.65724085  0.74422644  0.95280503]
  [ 0.22185243  0.21969498  0.31722055  0.50998096  0.54131707]
  [ 0.78368751  0.18323387  0.2906823   0.17414157  0.96490528]]

 [[ 0.89435886  0.96986971  0.71229997  0.37792392  0.38869377]
  [ 0.65646515  0.12495514  0.29072727  0.27348403  0.41487682]
  [ 0.09558783  0.12397421  0.97410633  0.14579298  0.24608502]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [14]:
b = np.ones((5,2,3))

#### 6. Print *b*.


In [15]:
print(b)

[[[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [16]:
print(a.size)
print(b.size)

30
30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [17]:
#We can't add them together because array a is different shape than array b.
sum_ab = a + b
print(sum_ab)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [5]:
import numpy as np
b = np.ones((5,2,3))
#print(b)

a = np.random.random((2,3,5))
#print(a)

#c = np.transpose(b)
c = np.transpose(a).shape
print(c)

d = np.transpose(b).shape
print(d)

# I cannot make the transposing work, so I'm creating b directly.

print()

c = np.ones ((2,3,5))
print(c)

(5, 3, 2)
(3, 2, 5)

[[[ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [6]:
d = a + c
print(d)

[[[ 1.07566888  1.1288069   1.41146058  1.03979293  1.95871146]
  [ 1.2714315   1.31629981  1.98807438  1.05444939  1.4514606 ]
  [ 1.62165228  1.64182964  1.91232016  1.4204024   1.74704965]]

 [[ 1.99312839  1.18089061  1.22351309  1.26588016  1.20977708]
  [ 1.28354406  1.46875418  1.14524621  1.69889359  1.62422895]
  [ 1.52235102  1.66033818  1.19529116  1.30610467  1.2451153 ]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [20]:
print('The values in array d is the addition of values in array a and c together.')
print('Array a')
print(a)
print()
print('Array d')
print(d)

The values in array d is the addition of values in array a and c together.
Array a
[[[ 0.42454399  0.06276251  0.30591682  0.62906359  0.17104209]
  [ 0.66871319  0.07204446  0.04632513  0.93650195  0.82055486]
  [ 0.85266631  0.34722768  0.83964711  0.53413651  0.61357496]]

 [[ 0.87053779  0.09414269  0.46875827  0.60251062  0.430647  ]
  [ 0.84778241  0.9475405   0.70692642  0.02930469  0.36697683]
  [ 0.73869878  0.01962573  0.37028891  0.24801848  0.4136856 ]]]

Array d
[[[ 1.42454399  1.06276251  1.30591682  1.62906359  1.17104209]
  [ 1.66871319  1.07204446  1.04632513  1.93650195  1.82055486]
  [ 1.85266631  1.34722768  1.83964711  1.53413651  1.61357496]]

 [[ 1.87053779  1.09414269  1.46875827  1.60251062  1.430647  ]
  [ 1.84778241  1.9475405   1.70692642  1.02930469  1.36697683]
  [ 1.73869878  1.01962573  1.37028891  1.24801848  1.4136856 ]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [7]:
e = a*c
print(e)

[[[ 0.07566888  0.1288069   0.41146058  0.03979293  0.95871146]
  [ 0.2714315   0.31629981  0.98807438  0.05444939  0.4514606 ]
  [ 0.62165228  0.64182964  0.91232016  0.4204024   0.74704965]]

 [[ 0.99312839  0.18089061  0.22351309  0.26588016  0.20977708]
  [ 0.28354406  0.46875418  0.14524621  0.69889359  0.62422895]
  [ 0.52235102  0.66033818  0.19529116  0.30610467  0.2451153 ]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [22]:
print('Array e is equal to array a because any number multiplied by 1 is equal to that number')
print('Array e')
print(e)
print()
print('Array a')
print(a)

Array e is equal to array a because any number multiplied by 1 is equal to that number
Array e
[[[ 0.42454399  0.06276251  0.30591682  0.62906359  0.17104209]
  [ 0.66871319  0.07204446  0.04632513  0.93650195  0.82055486]
  [ 0.85266631  0.34722768  0.83964711  0.53413651  0.61357496]]

 [[ 0.87053779  0.09414269  0.46875827  0.60251062  0.430647  ]
  [ 0.84778241  0.9475405   0.70692642  0.02930469  0.36697683]
  [ 0.73869878  0.01962573  0.37028891  0.24801848  0.4136856 ]]]

Array a
[[[ 0.42454399  0.06276251  0.30591682  0.62906359  0.17104209]
  [ 0.66871319  0.07204446  0.04632513  0.93650195  0.82055486]
  [ 0.85266631  0.34722768  0.83964711  0.53413651  0.61357496]]

 [[ 0.87053779  0.09414269  0.46875827  0.60251062  0.430647  ]
  [ 0.84778241  0.9475405   0.70692642  0.02930469  0.36697683]
  [ 0.73869878  0.01962573  0.37028891  0.24801848  0.4136856 ]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [8]:
print(d)
print()
d_max = np.max(d)
print('Max of array d is', d_max)

d_min = np.min(d)
print('Min of array d is', d_min)

d_mean = np.mean(d)
print('Mean of array d is', d_mean)

[[[ 1.07566888  1.1288069   1.41146058  1.03979293  1.95871146]
  [ 1.2714315   1.31629981  1.98807438  1.05444939  1.4514606 ]
  [ 1.62165228  1.64182964  1.91232016  1.4204024   1.74704965]]

 [[ 1.99312839  1.18089061  1.22351309  1.26588016  1.20977708]
  [ 1.28354406  1.46875418  1.14524621  1.69889359  1.62422895]
  [ 1.52235102  1.66033818  1.19529116  1.30610467  1.2451153 ]]]

Max of array d is 1.99312839086
Min of array d is 1.0397929262
Mean of array d is 1.43541557347


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [10]:
f = np.empty((2,3,5))
print(f)

[[[ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [11]:
#print('Max of array d is', d_max)
#print('Min of array d is', d_min)
#print('Mean of array d is', d_mean)
#print(d)
#print(f)

for index0 in range(len(d)):
    #print('index0 is', index0)
    #print('value0 is', d [index0])
    for index1 in range(len(d [index0])):
        #print('index1 is', index1)
        #print('value1 is', d [index0] [index1])
        for index2 in range(len(d [index0] [index1])):
            value = d [index0] [index1] [index2]
            if value > d_min and value < d_mean:
                f [index0] [index1] [index2] = 25
            elif value > d_mean and value < d_max:
                f [index0] [index1] [index2] = 75
            elif value == d_mean:
                f [index0] [index1] [index2] = 50
            elif value == d_min:
                f [index0] [index1] [index2] = 0
            elif value == d_max:
                f [index0] [index1] [index2] = 100

print(f)


[[[  25.   25.   25.    0.   75.]
  [  25.   25.   75.   25.   75.]
  [  75.   75.   75.   25.   75.]]

 [[ 100.   25.   25.   25.   25.]
  [  25.   75.   25.   75.   75.]
  [  75.   75.   25.   25.   25.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [26]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [15]:
new_f = []
for index0 in range(len(d)):
    new_lst0 = []
    for index1 in range(len(d [index0])):
        new_lst1 = []
        for index2 in range(len(d [index0] [index1])):
            value = d [index0] [index1] [index2]
            if value > d_min and value < d_mean:
                new_lst1.append('B')
            elif value > d_mean and value < d_max:
                new_lst1.append('D')
            elif value == d_mean:
                new_lst1.append('C')
            elif value == d_min:
                new_lst1.append('A')
            elif value == d_max:
                new_lst1.append('E')
        new_lst0.append(new_lst1)
    new_f.append(new_lst0)
print(np.array(new_f))

[[['B' 'B' 'B' 'A' 'D']
  ['B' 'B' 'D' 'B' 'D']
  ['D' 'D' 'D' 'B' 'D']]

 [['E' 'B' 'B' 'B' 'B']
  ['B' 'D' 'B' 'D' 'D']
  ['D' 'D' 'B' 'B' 'B']]]
