# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np 

#### 2. Print your NumPy version.

In [3]:
print(np.__version__)

1.18.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [5]:
a = np.random.random((2,3,5))
print(a)

[[[0.82914005 0.73022752 0.92111069 0.32862786 0.01158172]
  [0.76374561 0.0135134  0.59119504 0.84378944 0.8630819 ]
  [0.14616879 0.0067192  0.83363251 0.812448   0.56384069]]

 [[0.79409601 0.86405656 0.05439584 0.47762995 0.44637059]
  [0.87609842 0.51175731 0.39689264 0.53165345 0.35078769]
  [0.96658231 0.86097508 0.49569914 0.80319374 0.23297093]]]


In [21]:
a = np.random.randint(0,100,(2,3,5))
print(a)

[[[81 97 27 76 55]
  [58 66 91 55  7]
  [36 60 61 26 75]]

 [[54 10 97 25 90]
  [85 36  4 62 60]
  [35  8 87 51 59]]]


In [23]:
a = np.random.rand(2,3,5)
print(a)


[[[0.97563487 0.50517399 0.30394424 0.5893071  0.25582796]
  [0.46641282 0.06961479 0.77367968 0.86202717 0.16189783]
  [0.38863044 0.48212392 0.64879178 0.20682487 0.18868076]]

 [[0.49156409 0.06191512 0.30484022 0.97422225 0.263796  ]
  [0.47409253 0.00155048 0.18160505 0.59809199 0.93465114]
  [0.57290676 0.05566513 0.3817199  0.66226154 0.90092053]]]


#### 4. Print *a*.


In [24]:
print(a)

[[[0.97563487 0.50517399 0.30394424 0.5893071  0.25582796]
  [0.46641282 0.06961479 0.77367968 0.86202717 0.16189783]
  [0.38863044 0.48212392 0.64879178 0.20682487 0.18868076]]

 [[0.49156409 0.06191512 0.30484022 0.97422225 0.263796  ]
  [0.47409253 0.00155048 0.18160505 0.59809199 0.93465114]
  [0.57290676 0.05566513 0.3817199  0.66226154 0.90092053]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [44]:
b = np.ones((5,2,3))


#### 6. Print *b*.


In [35]:
print(b)
print(b.shape)


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
(5, 2, 3)


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [26]:
print(b.shape)
print(b.size)
print(a.shape)
print(a.size)

#it`s the same size, but not the same shape

(5, 2, 3)
30
(2, 3, 5)
30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [27]:
print(np.add(a,b))

# it`s not working because of the different shapes of the arrays

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [47]:
c = np.transpose(b, (1 ,2 ,0))
print(c)
print(c.shape)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
(2, 3, 5)


In [33]:
print(a)
print(a.shape)

[[[0.97563487 0.50517399 0.30394424 0.5893071  0.25582796]
  [0.46641282 0.06961479 0.77367968 0.86202717 0.16189783]
  [0.38863044 0.48212392 0.64879178 0.20682487 0.18868076]]

 [[0.49156409 0.06191512 0.30484022 0.97422225 0.263796  ]
  [0.47409253 0.00155048 0.18160505 0.59809199 0.93465114]
  [0.57290676 0.05566513 0.3817199  0.66226154 0.90092053]]]
(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [48]:
d = np.add(a,c)

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [49]:
print(a)
print(d)

[[[0.97563487 0.50517399 0.30394424 0.5893071  0.25582796]
  [0.46641282 0.06961479 0.77367968 0.86202717 0.16189783]
  [0.38863044 0.48212392 0.64879178 0.20682487 0.18868076]]

 [[0.49156409 0.06191512 0.30484022 0.97422225 0.263796  ]
  [0.47409253 0.00155048 0.18160505 0.59809199 0.93465114]
  [0.57290676 0.05566513 0.3817199  0.66226154 0.90092053]]]
[[[1.97563487 1.50517399 1.30394424 1.5893071  1.25582796]
  [1.46641282 1.06961479 1.77367968 1.86202717 1.16189783]
  [1.38863044 1.48212392 1.64879178 1.20682487 1.18868076]]

 [[1.49156409 1.06191512 1.30484022 1.97422225 1.263796  ]
  [1.47409253 1.00155048 1.18160505 1.59809199 1.93465114]
  [1.57290676 1.05566513 1.3817199  1.66226154 1.90092053]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [52]:
e = np.multiply(a, c)
print(e)

[[[0.97563487 0.50517399 0.30394424 0.5893071  0.25582796]
  [0.46641282 0.06961479 0.77367968 0.86202717 0.16189783]
  [0.38863044 0.48212392 0.64879178 0.20682487 0.18868076]]

 [[0.49156409 0.06191512 0.30484022 0.97422225 0.263796  ]
  [0.47409253 0.00155048 0.18160505 0.59809199 0.93465114]
  [0.57290676 0.05566513 0.3817199  0.66226154 0.90092053]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [56]:
print(a.size)
print(e.size)
print(a.shape)
print(e.shape)

# its the same because multiplied by one

30
30
(2, 3, 5)
(2, 3, 5)


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [95]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(d_max)
print(d_min)
print(d_mean)

print(d)

1.9756348675646818
1.0015504783349432
1.4579458313875968
[[[1.97563487 1.50517399 1.30394424 1.5893071  1.25582796]
  [1.46641282 1.06961479 1.77367968 1.86202717 1.16189783]
  [1.38863044 1.48212392 1.64879178 1.20682487 1.18868076]]

 [[1.49156409 1.06191512 1.30484022 1.97422225 1.263796  ]
  [1.47409253 1.00155048 1.18160505 1.59809199 1.93465114]
  [1.57290676 1.05566513 1.3817199  1.66226154 1.90092053]]]


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [98]:
f = np.empty((2,3,5))
print(f)

[[[1.97563487 1.50517399 1.30394424 1.5893071  1.25582796]
  [1.46641282 1.06961479 1.77367968 1.86202717 1.16189783]
  [1.38863044 1.48212392 1.64879178 1.20682487 1.18868076]]

 [[1.49156409 1.06191512 1.30484022 1.97422225 1.263796  ]
  [1.47409253 1.00155048 1.18160505 1.59809199 1.93465114]
  [1.57290676 1.05566513 1.3817199  1.66226154 1.90092053]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [99]:
f[(d_min < d) & (d < d_mean)] = 25
f[(d_mean < d) & (d < d_max)] = 75
f[(d_mean == d)] = 50
f[(d_min == d)] = 0
f[(d_max == d)] = 100

In [100]:
print(f)

[[[100.  75.  25.  75.  25.]
  [ 75.  25.  75.  75.  25.]
  [ 25.  75.  75.  25.  25.]]

 [[ 75.  25.  25.  75.  25.]
  [ 75.   0.  25.  75.  75.]
  [ 75.  25.  25.  75.  75.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [101]:
z = np.empty_like(d, dtype =str)

In [102]:
print(z)

[[['' '' '' '' '']
  ['' '' '' '' '']
  ['' '' '' '' '']]

 [['' '' '' '' '']
  ['' '' '' '' '']
  ['' '' '' '' '']]]


In [103]:
z[(d_min < d) & (d < d_mean)] = "A"
z[(d_mean < d) & (d < d_max)] = "B"
z[(d_mean == d)] = "C"
z[(d_min == d)] = "D"
z[(d_max == d)] = "E"

In [104]:
print(z)

[[['E' 'B' 'A' 'B' 'A']
  ['B' 'A' 'B' 'B' 'A']
  ['A' 'B' 'B' 'A' 'A']]

 [['B' 'A' 'A' 'B' 'A']
  ['B' 'D' 'A' 'B' 'B']
  ['B' 'A' 'A' 'B' 'B']]]
