# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here

# Install a pip package in the current Jupyter kernel
import sys
!{sys.executable} -m pip install numpy
!{sys.executable} -m pip install --upgrade pip

import numpy as np

Requirement already up-to-date: pip in /usr/local/Cellar/jupyterlab/2.0.1/libexec/lib/python3.7/site-packages (20.1)


#### 2. Print your NumPy version.

In [2]:
# your code here

np.version

<module 'numpy.version' from '/usr/local/Cellar/jupyterlab/2.0.1/libexec/lib/python3.7/site-packages/numpy/version.py'>

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
# Return random floats in the half-open interval [0.0, 1.0).

a = np.random.random((2,3,5))

print(a)

[[[0.1344652  0.86197395 0.28119084 0.37715705 0.9279015 ]
  [0.68712173 0.70092913 0.61578695 0.66233873 0.45475793]
  [0.9358892  0.86362963 0.04855443 0.8926662  0.81468611]]

 [[0.65039646 0.89792442 0.29127957 0.4409727  0.89139698]
  [0.80287446 0.90451471 0.59023978 0.32431046 0.89363865]
  [0.43891235 0.10292871 0.57883508 0.78049376 0.24549723]]]


In [29]:
# Method 2
# Create an array of the given shape and propagate it with random samples from a uniform distribution over [0, 1).

k = np.random.rand(2,3,5)

print(k)

[[[0.20398046 0.99231524 0.51294299 0.79694752 0.84391335]
  [0.08780005 0.37535425 0.81350989 0.49727008 0.01938208]
  [0.36463553 0.88006261 0.20755586 0.75390633 0.44352492]]

 [[0.93512458 0.91378563 0.45780157 0.81274896 0.09131239]
  [0.57597355 0.5014077  0.24610553 0.29370798 0.19673023]
  [0.05074222 0.38950173 0.75055057 0.19967758 0.77286544]]]


In [33]:
# Method 3
# Create an array of random integers in [0, 10)

m = np.random.randint(10, size=(2,3,5))

print(m)

[[[8 1 8 9 5]
  [5 4 0 6 8]
  [4 7 7 0 0]]

 [[3 6 5 8 9]
  [9 3 9 0 8]
  [5 8 8 2 2]]]


#### 4. Print *a*.


In [6]:
# your code here

print(a)

[[[0.1344652  0.86197395 0.28119084 0.37715705 0.9279015 ]
  [0.68712173 0.70092913 0.61578695 0.66233873 0.45475793]
  [0.9358892  0.86362963 0.04855443 0.8926662  0.81468611]]

 [[0.65039646 0.89792442 0.29127957 0.4409727  0.89139698]
  [0.80287446 0.90451471 0.59023978 0.32431046 0.89363865]
  [0.43891235 0.10292871 0.57883508 0.78049376 0.24549723]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here

b = np.full((5, 2, 3), 1)

#### 6. Print *b*.


In [8]:
# your code here
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here

print(a.size == b.size)

True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here

# The arrays have different shapes
print("a shape, b shape respectively: ", a.shape, b.shape)

a shape, b shape respectively:  (2, 3, 5) (5, 2, 3)


In [11]:
print(np.add(a, b))

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [12]:
# your code here

c = b.reshape(2,3,5)
print("c shape", c.shape)
print(c)

c shape (2, 3, 5)
[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [13]:
# your code/answer here

d = np.add(a, c)

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [14]:
# your code/answer here
print("Array a : \n", a, "\n\n Array d : \n", d)

# Each value in the array a is the one from array a +1.

Array a : 
 [[[0.1344652  0.86197395 0.28119084 0.37715705 0.9279015 ]
  [0.68712173 0.70092913 0.61578695 0.66233873 0.45475793]
  [0.9358892  0.86362963 0.04855443 0.8926662  0.81468611]]

 [[0.65039646 0.89792442 0.29127957 0.4409727  0.89139698]
  [0.80287446 0.90451471 0.59023978 0.32431046 0.89363865]
  [0.43891235 0.10292871 0.57883508 0.78049376 0.24549723]]] 

 Array d : 
 [[[1.1344652  1.86197395 1.28119084 1.37715705 1.9279015 ]
  [1.68712173 1.70092913 1.61578695 1.66233873 1.45475793]
  [1.9358892  1.86362963 1.04855443 1.8926662  1.81468611]]

 [[1.65039646 1.89792442 1.29127957 1.4409727  1.89139698]
  [1.80287446 1.90451471 1.59023978 1.32431046 1.89363865]
  [1.43891235 1.10292871 1.57883508 1.78049376 1.24549723]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [15]:
# your code here
e = np.multiply(a, c)

#### 13. Does *e* equal to *a*? Why or why not?


In [16]:
# your code/answer here

a == e

# Multiplication by 1 does not change the value.

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [17]:
# your code here

print(np.max(d), np.min(d), np.mean(d))

d_max = np.max(d) 
d_min = np.min(d)
d_mean = np.mean(d)

1.9358891964745135 1.0485544333452452 1.6031087965340547


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [18]:
# your code here

f = np.empty((2,3,5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [19]:
# your code here

# The order of assigning values is important, e.g. max value first gets assigned 75, then 100.
# The alternative would be to add double condition (between min and mean, etc.)

f[d > d_mean] = 75
f[d < d_mean] = 25
f[d == d_max] = 100
f[d == d_mean] = 50
f[d == d_min] = 0

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [20]:
# your code here

print("Array d: \n", d)
print("Array f: \n", f)

Array d: 
 [[[1.1344652  1.86197395 1.28119084 1.37715705 1.9279015 ]
  [1.68712173 1.70092913 1.61578695 1.66233873 1.45475793]
  [1.9358892  1.86362963 1.04855443 1.8926662  1.81468611]]

 [[1.65039646 1.89792442 1.29127957 1.4409727  1.89139698]
  [1.80287446 1.90451471 1.59023978 1.32431046 1.89363865]
  [1.43891235 1.10292871 1.57883508 1.78049376 1.24549723]]]
Array f: 
 [[[ 25.  75.  25.  25.  75.]
  [ 75.  75.  75.  75.  25.]
  [100.  75.   0.  75.  75.]]

 [[ 75.  75.  25.  25.  75.]
  [ 75.  75.  25.  25.  75.]
  [ 25.  25.  25.  75.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [35]:
# your code here

# I suppose I could convert f to a list, turn floats to strings,  and then reassign the values in the loop. (not finished)

f_list = f.tolist()
f_list

[[[25.0, 75.0, 25.0, 25.0, 75.0],
  [75.0, 75.0, 75.0, 75.0, 25.0],
  [100.0, 75.0, 0.0, 75.0, 75.0]],
 [[75.0, 75.0, 25.0, 25.0, 75.0],
  [75.0, 75.0, 25.0, 25.0, 75.0],
  [25.0, 25.0, 25.0, 75.0, 25.0]]]