# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [3]:
# your code here
np.version.version

'1.19.2'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [12]:
# Method 1
A = np.random.randn(2,3,5)

[[[-0.50984651  0.48446228 -1.78824515  0.34950598 -1.1815681 ]
  [ 0.3332354  -0.18913144 -1.82025376  1.69107763 -1.35685626]
  [ 0.52464229 -0.12646385 -0.8189204  -0.49502873  0.06258117]]

 [[-0.73335218 -0.33315884  0.85935823  2.80314125  2.34303045]
  [-2.08561776 -1.28902309 -0.5765454   0.22142779  0.45178962]
  [ 1.99358054  0.01856017  0.17633215 -0.76329711  0.99122226]]]
[[[0.49680766 0.55381271 0.86579155 0.21458602 0.75825219]
  [0.55194408 0.09083649 0.54688034 0.17250208 0.75417896]
  [0.72770935 0.2407157  0.33155438 0.78242013 0.42248447]]

 [[0.01153402 0.52235036 0.74400014 0.18354748 0.85679581]
  [0.80954466 0.16557261 0.56739215 0.17225349 0.6684927 ]
  [0.11867635 0.17159624 0.7926703  0.46338918 0.37414708]]]
[[[0.53976316 0.48454076 0.62709213 0.68805149 0.19956626]
  [0.87118575 0.13244108 0.48327023 0.68866844 0.59084473]
  [0.64685185 0.66577192 0.54008364 0.23044377 0.63985018]]

 [[0.84722993 0.29615362 0.75888318 0.55811411 0.20051464]
  [0.3091574  0.

In [ ]:
# Method 2
print(np.random.random((2,3,5)))

In [ ]:
# Method 3
print(np.random.rand(2,3,5))

#### 4. Print *a*.


In [13]:
# your code here
print(A)

[[[-0.50984651  0.48446228 -1.78824515  0.34950598 -1.1815681 ]
  [ 0.3332354  -0.18913144 -1.82025376  1.69107763 -1.35685626]
  [ 0.52464229 -0.12646385 -0.8189204  -0.49502873  0.06258117]]

 [[-0.73335218 -0.33315884  0.85935823  2.80314125  2.34303045]
  [-2.08561776 -1.28902309 -0.5765454   0.22142779  0.45178962]
  [ 1.99358054  0.01856017  0.17633215 -0.76329711  0.99122226]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [15]:
# your code here
B = np.ones((5,2,3))

#### 6. Print *b*.


In [16]:
# your code here
print(B)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [18]:
# your code here
np.shape(A) == np.shape(B)

False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [19]:
# your answer here
# no not the same shape

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [27]:
# your code here
C = np.transpose(B,(1,2,0))
print(np.shape(A))
print(np.shape(B))
print(np.shape(C))

(2, 3, 5)
(5, 2, 3)
(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [28]:
# your code/answer here
D = C + A

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [31]:
# your code/answer here
print(D)
print(A)
# there is a difference of 1 with all elements

[[[ 0.49015349  1.48446228 -0.78824515  1.34950598 -0.1815681 ]
  [ 1.3332354   0.81086856 -0.82025376  2.69107763 -0.35685626]
  [ 1.52464229  0.87353615  0.1810796   0.50497127  1.06258117]]

 [[ 0.26664782  0.66684116  1.85935823  3.80314125  3.34303045]
  [-1.08561776 -0.28902309  0.4234546   1.22142779  1.45178962]
  [ 2.99358054  1.01856017  1.17633215  0.23670289  1.99122226]]]
[[[-0.50984651  0.48446228 -1.78824515  0.34950598 -1.1815681 ]
  [ 0.3332354  -0.18913144 -1.82025376  1.69107763 -1.35685626]
  [ 0.52464229 -0.12646385 -0.8189204  -0.49502873  0.06258117]]

 [[-0.73335218 -0.33315884  0.85935823  2.80314125  2.34303045]
  [-2.08561776 -1.28902309 -0.5765454   0.22142779  0.45178962]
  [ 1.99358054  0.01856017  0.17633215 -0.76329711  0.99122226]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [32]:
# your code here
E = A * C

#### 13. Does *e* equal to *a*? Why or why not?


In [34]:
# your code/answer here
print(A)
print(E)
print(C) # C = 1 all elements

[[[-0.50984651  0.48446228 -1.78824515  0.34950598 -1.1815681 ]
  [ 0.3332354  -0.18913144 -1.82025376  1.69107763 -1.35685626]
  [ 0.52464229 -0.12646385 -0.8189204  -0.49502873  0.06258117]]

 [[-0.73335218 -0.33315884  0.85935823  2.80314125  2.34303045]
  [-2.08561776 -1.28902309 -0.5765454   0.22142779  0.45178962]
  [ 1.99358054  0.01856017  0.17633215 -0.76329711  0.99122226]]]
[[[-0.50984651  0.48446228 -1.78824515  0.34950598 -1.1815681 ]
  [ 0.3332354  -0.18913144 -1.82025376  1.69107763 -1.35685626]
  [ 0.52464229 -0.12646385 -0.8189204  -0.49502873  0.06258117]]

 [[-0.73335218 -0.33315884  0.85935823  2.80314125  2.34303045]
  [-2.08561776 -1.28902309 -0.5765454   0.22142779  0.45178962]
  [ 1.99358054  0.01856017  0.17633215 -0.76329711  0.99122226]]]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [37]:
# your code here
d_max = np.max(D)
d_min = np.min(D)
d_mean = np.mean(D)
print(d_mean)

0.9745546221095459


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [40]:
# your code here
F = np.empty((2,3,5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [51]:
# your code here

def getValue(x, myMin, myMax, myMean):
    if x > myMin and x < myMean:
        return 25
    elif x > myMean and x < myMax:
        return 75
    elif x == myMean:
        return 50
    elif x == myMin:
        return 0
    else:
        return 100
    
F = [[[getValue(element, d_min, d_max, d_mean) for element in line] for line in TwoDArray] for TwoDArray in D]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [52]:
# your code here
print(D)
print(F)

[[[ 0.49015349  1.48446228 -0.78824515  1.34950598 -0.1815681 ]
  [ 1.3332354   0.81086856 -0.82025376  2.69107763 -0.35685626]
  [ 1.52464229  0.87353615  0.1810796   0.50497127  1.06258117]]

 [[ 0.26664782  0.66684116  1.85935823  3.80314125  3.34303045]
  [-1.08561776 -0.28902309  0.4234546   1.22142779  1.45178962]
  [ 2.99358054  1.01856017  1.17633215  0.23670289  1.99122226]]]
[[[25, 75, 25, 75, 25], [75, 25, 25, 75, 25], [75, 25, 25, 25, 75]], [[25, 25, 75, 100, 75], [0, 25, 25, 75, 75], [75, 75, 75, 25, 75]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [53]:
# your code here
def getString(x, myMin, myMax, myMean):
    if x > myMin and x < myMean:
        return 'B'
    elif x > myMean and x < myMax:
        return 'D'
    elif x == myMean:
        return 'C'
    elif x == myMin:
        return 'A'
    else:
        return 'E'
    
F = [[[getString(element, d_min, d_max, d_mean) for element in line] for line in TwoDArray] for TwoDArray in D]


In [54]:
print(F)

[[['B', 'D', 'B', 'D', 'B'], ['D', 'B', 'B', 'D', 'B'], ['D', 'B', 'B', 'B', 'D']], [['B', 'B', 'D', 'E', 'D'], ['A', 'B', 'B', 'D', 'D'], ['D', 'D', 'D', 'B', 'D']]]


In [62]:
"""Write a function insert_dash(num) / insertDash(num) / InsertDash(int num) that will insert dashes ('-')
between each two odd numbers in num. 
For example: if num is 454793 the output should be 4547-9-3. Don't count zero as an odd number.

Note that the number will always be non-negative (>= 0).
"""


def getTwoOdds(number):
    isPreviousOdd = False
    result = ''
    for element in str(number):
        isCurrentOdd = int(element) % 2 != 0
        if isCurrentOdd and isPreviousOdd:
            result+= '-'+element
        else:
            result+= element
        isPreviousOdd = isCurrentOdd
    return result
        
getTwoOdds(454793)

'4547-9-3'