# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [5]:
# your code here

import sys
!{sys.executable} -m pip install numpy

     |████████████████████████████████| 15.3 MB 1.6 MB/s eta 0:00:01
You should consider upgrading via the '/usr/local/Cellar/jupyterlab/2.1.1/libexec/bin/python3.8 -m pip install --upgrade pip' command.


In [6]:
import numpy as np

#### 2. Print your NumPy version.

In [7]:
# your code here
print(np.__version__)

1.19.0


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [15]:
# Method 1
a = np.random.random((2,3,5))
a

array([[[0.64820706, 0.53531577, 0.65387079, 0.92762719, 0.06830592],
        [0.50200499, 0.1807917 , 0.13175972, 0.29502111, 0.40635537],
        [0.58035274, 0.06467495, 0.52657582, 0.37974381, 0.6314357 ]],

       [[0.70604603, 0.8563727 , 0.57392079, 0.77557983, 0.61709616],
        [0.79908442, 0.6412618 , 0.30309882, 0.73146075, 0.14231708],
        [0.47396503, 0.5306513 , 0.53367308, 0.14440283, 0.91226628]]])

In [13]:
# Method 2
a = np.random.randn(2,3,5)
a

array([[[-0.50431619,  0.54775706,  1.78611289, -0.62410432,
          1.49031279],
        [ 0.48520279,  0.38821742, -1.39286016, -0.56726177,
          0.21665711],
        [ 0.0293655 , -1.06017871, -1.46816325, -0.51089867,
          0.30450615]],

       [[-2.14106428,  1.44737059, -0.94271115, -1.57175289,
          0.93626026],
        [-0.43906123, -1.18161044,  1.4098245 , -1.14037066,
         -0.28054672],
        [ 1.03471732, -0.21683331,  0.50830274,  0.77248255,
          0.46551884]]])

In [22]:
# Method 3
a = np.random.rand(2,3,5)
a

array([[[0.43622576, 0.07406879, 0.97857081, 0.7433199 , 0.04173123],
        [0.12927084, 0.26952769, 0.80342595, 0.93720033, 0.54055205],
        [0.36100397, 0.77537287, 0.52590501, 0.74653447, 0.2351197 ]],

       [[0.96266482, 0.48161101, 0.47339318, 0.32420335, 0.96654068],
        [0.23044001, 0.48452695, 0.76672781, 0.34363525, 0.46811442],
        [0.37741531, 0.61698781, 0.29043601, 0.11963427, 0.89202027]]])

#### 4. Print *a*.


In [23]:
# your code here
a

array([[[0.43622576, 0.07406879, 0.97857081, 0.7433199 , 0.04173123],
        [0.12927084, 0.26952769, 0.80342595, 0.93720033, 0.54055205],
        [0.36100397, 0.77537287, 0.52590501, 0.74653447, 0.2351197 ]],

       [[0.96266482, 0.48161101, 0.47339318, 0.32420335, 0.96654068],
        [0.23044001, 0.48452695, 0.76672781, 0.34363525, 0.46811442],
        [0.37741531, 0.61698781, 0.29043601, 0.11963427, 0.89202027]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [30]:
# your code here
b = np.ones((5, 2, 3))

#### 6. Print *b*.


In [28]:
# your code here
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [33]:
# your code here
print (a.size)
print (b.size)

30
30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [36]:
# No, because they don't have the same structure, 
# one is (2,3,5) and the other(5,2,3) 
print(a + b)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [46]:
# Transpose b to same strucure than a
c = np.reshape(b,[2, 3, 5])
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [47]:
# Add two arrays
d = a + c
print(d)

[[[1.43622576 1.07406879 1.97857081 1.7433199  1.04173123]
  [1.12927084 1.26952769 1.80342595 1.93720033 1.54055205]
  [1.36100397 1.77537287 1.52590501 1.74653447 1.2351197 ]]

 [[1.96266482 1.48161101 1.47339318 1.32420335 1.96654068]
  [1.23044001 1.48452695 1.76672781 1.34363525 1.46811442]
  [1.37741531 1.61698781 1.29043601 1.11963427 1.89202027]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [49]:
# your code/answer here
print (a)
print (d)

d == a + 1

[[[0.43622576 0.07406879 0.97857081 0.7433199  0.04173123]
  [0.12927084 0.26952769 0.80342595 0.93720033 0.54055205]
  [0.36100397 0.77537287 0.52590501 0.74653447 0.2351197 ]]

 [[0.96266482 0.48161101 0.47339318 0.32420335 0.96654068]
  [0.23044001 0.48452695 0.76672781 0.34363525 0.46811442]
  [0.37741531 0.61698781 0.29043601 0.11963427 0.89202027]]]
[[[1.43622576 1.07406879 1.97857081 1.7433199  1.04173123]
  [1.12927084 1.26952769 1.80342595 1.93720033 1.54055205]
  [1.36100397 1.77537287 1.52590501 1.74653447 1.2351197 ]]

 [[1.96266482 1.48161101 1.47339318 1.32420335 1.96654068]
  [1.23044001 1.48452695 1.76672781 1.34363525 1.46811442]
  [1.37741531 1.61698781 1.29043601 1.11963427 1.89202027]]]


array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [50]:
# your code here
e = a * c 
print(e)

[[[0.43622576 0.07406879 0.97857081 0.7433199  0.04173123]
  [0.12927084 0.26952769 0.80342595 0.93720033 0.54055205]
  [0.36100397 0.77537287 0.52590501 0.74653447 0.2351197 ]]

 [[0.96266482 0.48161101 0.47339318 0.32420335 0.96654068]
  [0.23044001 0.48452695 0.76672781 0.34363525 0.46811442]
  [0.37741531 0.61698781 0.29043601 0.11963427 0.89202027]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [55]:
# your code/answer here
(a == e).all()

# Yes ! 

True

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [58]:
# your code here
# Minimum 
d_min = (np.min(d))
# maximum
d_max = (np.max(d))
# mean 
d_mean = (np.mean(d))

In [60]:
d_min

1.0417312306716129

In [62]:
d_max

1.9785708076414237

In [63]:
d_mean

1.5132060167887458

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [68]:
# Label value in d 

f = np.empty([2, 3, 5])
print(f)

[[[0.43622576 0.07406879 0.97857081 0.7433199  0.04173123]
  [0.12927084 0.26952769 0.80342595 0.93720033 0.54055205]
  [0.36100397 0.77537287 0.52590501 0.74653447 0.2351197 ]]

 [[0.96266482 0.48161101 0.47339318 0.32420335 0.96654068]
  [0.23044001 0.48452695 0.76672781 0.34363525 0.46811442]
  [0.37741531 0.61698781 0.29043601 0.11963427 0.89202027]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. 

If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. 

If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. 

Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. 

Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. 

In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [96]:
# your code here
f [(d > d_min) & (d < d_mean)] = 25
f [(d > d_mean) & (d < d_max)] = 75
f [(d == d_mean)] = 50
f [(d == d_min)] = 0
f [(d == d_max)] = 100

In [97]:
f

array([[[ 25.,  25., 100.,  75.,   0.],
        [ 25.,  25.,  75.,  75.,  75.],
        [ 25.,  75.,  75.,  75.,  25.]],

       [[ 75.,  25.,  25.,  25.,  75.],
        [ 25.,  25.,  75.,  25.,  25.],
        [ 25.,  75.,  25.,  25.,  75.]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [98]:
f

array([[[ 25.,  25., 100.,  75.,   0.],
        [ 25.,  25.,  75.,  75.,  75.],
        [ 25.,  75.,  75.,  75.,  25.]],

       [[ 75.,  25.,  25.,  25.,  75.],
        [ 25.,  25.,  75.,  25.,  25.],
        [ 25.,  75.,  25.,  25.,  75.]]])

In [99]:
d

array([[[1.43622576, 1.07406879, 1.97857081, 1.7433199 , 1.04173123],
        [1.12927084, 1.26952769, 1.80342595, 1.93720033, 1.54055205],
        [1.36100397, 1.77537287, 1.52590501, 1.74653447, 1.2351197 ]],

       [[1.96266482, 1.48161101, 1.47339318, 1.32420335, 1.96654068],
        [1.23044001, 1.48452695, 1.76672781, 1.34363525, 1.46811442],
        [1.37741531, 1.61698781, 1.29043601, 1.11963427, 1.89202027]]])

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [102]:
# your code here
g = np.empty((2, 3, 5), dtype = "str")
g [(d > d_min) & (d < d_mean)] = "A"
g [(d > d_mean) & (d < d_max)] = "B"
g [(d == d_mean)] = "C"
g [(d == d_min)] = "D"
g [(d == d_max)] = "E"
print(g)

[[['A' 'A' 'E' 'B' 'D']
  ['A' 'A' 'B' 'B' 'B']
  ['A' 'B' 'B' 'B' 'A']]

 [['B' 'A' 'A' 'A' 'B']
  ['A' 'A' 'B' 'A' 'A']
  ['A' 'B' 'A' 'A' 'B']]]
