# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.17.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a = np.random.random((2,3,5))
# print(a)

In [4]:
# Method 2
c = np.random.rand(2,3,5)
# print(c)

In [5]:
# Method 3
d = np.random.randint(1, 100,(2,3,5))
# print(d)

#### 4. Print *a*.


In [6]:
# your code here
print(a)

[[[0.97611251 0.26631981 0.17968307 0.63217379 0.75777925]
  [0.26264112 0.97487408 0.93537228 0.47012787 0.12485352]
  [0.2975394  0.43757875 0.56631236 0.71937598 0.08571079]]

 [[0.75133573 0.23393584 0.65834864 0.06820984 0.5038705 ]
  [0.79558933 0.92526205 0.20968568 0.49255126 0.27823094]
  [0.24780673 0.84736596 0.74876427 0.27404087 0.17566826]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
b = np.ones((5,2,3), dtype=int)

#### 6. Print *b*.


In [8]:
# your code here
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here
print('It is', (a.size == b.size), 'that a and b have the same size.')

It is True that a and b have the same size.


#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here
np.add(a,b)
#no we cannot add them as they not have the same shape

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here
# print(a)
# print(b)
c = np.transpose(b, (1,2,0))
# print(c)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here
d = np.add(a,c)
# print(d)
# This works now as the arrays have thesame shape and size

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here
print(a) 
print('\n')
print(d)
# a difference of 1 in each element (difference is array c)
# print(np.subtract(d,a))

[[[0.97611251 0.26631981 0.17968307 0.63217379 0.75777925]
  [0.26264112 0.97487408 0.93537228 0.47012787 0.12485352]
  [0.2975394  0.43757875 0.56631236 0.71937598 0.08571079]]

 [[0.75133573 0.23393584 0.65834864 0.06820984 0.5038705 ]
  [0.79558933 0.92526205 0.20968568 0.49255126 0.27823094]
  [0.24780673 0.84736596 0.74876427 0.27404087 0.17566826]]]


[[[1.97611251 1.26631981 1.17968307 1.63217379 1.75777925]
  [1.26264112 1.97487408 1.93537228 1.47012787 1.12485352]
  [1.2975394  1.43757875 1.56631236 1.71937598 1.08571079]]

 [[1.75133573 1.23393584 1.65834864 1.06820984 1.5038705 ]
  [1.79558933 1.92526205 1.20968568 1.49255126 1.27823094]
  [1.24780673 1.84736596 1.74876427 1.27404087 1.17566826]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here
e = np.multiply(a,c)
# print(e)

#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here
print('Sum of both arrays are equal:', np.sum(a) == np.sum(e))
print('Size of both arrays are equal:', a.size == e.size)
print('Shape of both arrays are equal:', a.shape == e.shape)

Sum of both arrays are equal: True
Size of both arrays are equal: True
Shape of both arrays are equal: True


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [19]:
# your code here
print(d)
d_max = np.max(d)
# print(d_max)
d_min = np.min(d)
# print(d_min)
d_mean = np.mean(d)
# print(d_mean)

[[[1.97611251 1.26631981 1.17968307 1.63217379 1.75777925]
  [1.26264112 1.97487408 1.93537228 1.47012787 1.12485352]
  [1.2975394  1.43757875 1.56631236 1.71937598 1.08571079]]

 [[1.75133573 1.23393584 1.65834864 1.06820984 1.5038705 ]
  [1.79558933 1.92526205 1.20968568 1.49255126 1.27823094]
  [1.24780673 1.84736596 1.74876427 1.27404087 1.17566826]]]


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [25]:
# your code here
f = np.empty([2,3,5])
print(f)

[[[1.97611251 1.26631981 1.17968307 1.63217379 1.75777925]
  [1.26264112 1.97487408 1.93537228 1.47012787 1.12485352]
  [1.2975394  1.43757875 1.56631236 1.71937598 1.08571079]]

 [[1.75133573 1.23393584 1.65834864 1.06820984 1.5038705 ]
  [1.79558933 1.92526205 1.20968568 1.49255126 1.27823094]
  [1.24780673 1.84736596 1.74876427 1.27404087 1.17566826]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [37]:
# your code here
for i in d:
    first = enumerate(i)
#     print(list(first))
    for j in i:
        second = enumerate(j)
        print(list(first), list(second))
#         for k in j:
#             if d_mean > k > d_min:
#                 f[index(k)] = 25
# indexes = [i for i,x in enumerate(xs) if x == 'foo']



# f[0,0,0] =100             
# print(f)

[(0, array([1.97611251, 1.26631981, 1.17968307, 1.63217379, 1.75777925])), (1, array([1.26264112, 1.97487408, 1.93537228, 1.47012787, 1.12485352])), (2, array([1.2975394 , 1.43757875, 1.56631236, 1.71937598, 1.08571079]))] [(0, 1.9761125063682523), (1, 1.266319808150934), (2, 1.1796830736332171), (3, 1.6321737857311287), (4, 1.7577792536312526)]
[] [(0, 1.2626411197342966), (1, 1.9748740762514778), (2, 1.9353722839108634), (3, 1.4701278665310455), (4, 1.1248535178341257)]
[] [(0, 1.2975393977820981), (1, 1.4375787490695888), (2, 1.5663123594413395), (3, 1.719375976641913), (4, 1.0857107878832832)]
[(0, array([1.75133573, 1.23393584, 1.65834864, 1.06820984, 1.5038705 ])), (1, array([1.79558933, 1.92526205, 1.20968568, 1.49255126, 1.27823094])), (2, array([1.24780673, 1.84736596, 1.74876427, 1.27404087, 1.17566826]))] [(0, 1.7513357340380207), (1, 1.2339358449862683), (2, 1.6583486388500481), (3, 1.0682098356023721), (4, 1.5038705032398694)]
[] [(0, 1.7955893349627032), (1, 1.92526204751

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here